/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-nocheck

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docusaurusSidebar: [{ type: "autogenerated", dirName: "docusaurus" }],
  docusaurusZhSidebar: [{ type: "autogenerated", dirName: "zh/docusaurus" }],
  designSidebar: [{ type: "autogenerated", dirName: "design" }],
  designZhSidebar: [{ type: "autogenerated", dirName: "zh/design" }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
